name: Run Jest tests with Docker Compose
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker images
        run: docker-compose build
      - name: Start containers in background
        run: docker-compose up -d
      - name: Wait for database to be ready
        run: |
          while ! nc -w 1 postgres 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      - name: Call healthz endpoint
        run: curl -f http://localhost:3000/healthz || exit 1
      - name: Stop containers
        run: docker-compose down